<?php

namespace AppBundle\Repository;

/**
 * services_connectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class services_connectionRepository extends \Doctrine\ORM\EntityRepository
{
}
