<?php

namespace AppBundle\Repository;

/**
 * visitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class visitRepository extends \Doctrine\ORM\EntityRepository
{
}
